In [21]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
sent = ['the glass of milk',
       'the glass of juice',
       'the cup of tea',
       'I am a good boy',
       'I am a good developer',
       'understand the meaning of word',
       'your videos are good']

In [7]:
voc_size=10000

In [8]:
one_hot_repr = [one_hot(words,voc_size)for words in sent]

In [9]:
one_hot_repr

[[7343, 6848, 722, 7495],
 [7343, 6848, 722, 6920],
 [7343, 137, 722, 3563],
 [1053, 9305, 5080, 5610, 4624],
 [1053, 9305, 5080, 5610, 2038],
 [8594, 7343, 7749, 722, 606],
 [9095, 8793, 9557, 5610]]

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_len = 8
embedded_doc = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_len)

In [13]:
embedded_doc

array([[   0,    0,    0,    0, 7343, 6848,  722, 7495],
       [   0,    0,    0,    0, 7343, 6848,  722, 6920],
       [   0,    0,    0,    0, 7343,  137,  722, 3563],
       [   0,    0,    0, 1053, 9305, 5080, 5610, 4624],
       [   0,    0,    0, 1053, 9305, 5080, 5610, 2038],
       [   0,    0,    0, 8594, 7343, 7749,  722,  606],
       [   0,    0,    0,    0, 9095, 8793, 9557, 5610]])

In [14]:
dim = 10

In [15]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.predict(embedded_doc)

1/1 [==============================] - 2s 2s/step


array([[[-0.04679673,  0.01039904,  0.04844381, -0.03644277,
          0.04247322,  0.04932361, -0.00382499, -0.02198377,
         -0.02290235, -0.00016351],
        [-0.04679673,  0.01039904,  0.04844381, -0.03644277,
          0.04247322,  0.04932361, -0.00382499, -0.02198377,
         -0.02290235, -0.00016351],
        [-0.04679673,  0.01039904,  0.04844381, -0.03644277,
          0.04247322,  0.04932361, -0.00382499, -0.02198377,
         -0.02290235, -0.00016351],
        [-0.04679673,  0.01039904,  0.04844381, -0.03644277,
          0.04247322,  0.04932361, -0.00382499, -0.02198377,
         -0.02290235, -0.00016351],
        [-0.0372941 , -0.03828514,  0.00622058, -0.00144024,
         -0.01045423, -0.02724336, -0.02563229,  0.0025424 ,
          0.04759748, -0.01440148],
        [ 0.04508236, -0.00846624,  0.04136162, -0.0256164 ,
          0.04415221,  0.03130234,  0.03808018,  0.03918136,
         -0.00148093,  0.02065933],
        [ 0.01744771,  0.04932345,  0.01297107, -0.0

In [20]:
model.predict(embedded_doc[[0][0]])

1/1 [==============================] - 0s 31ms/step


array([[-0.04679673,  0.01039904,  0.04844381, -0.03644277,  0.04247322,
         0.04932361, -0.00382499, -0.02198377, -0.02290235, -0.00016351],
       [-0.04679673,  0.01039904,  0.04844381, -0.03644277,  0.04247322,
         0.04932361, -0.00382499, -0.02198377, -0.02290235, -0.00016351],
       [-0.04679673,  0.01039904,  0.04844381, -0.03644277,  0.04247322,
         0.04932361, -0.00382499, -0.02198377, -0.02290235, -0.00016351],
       [-0.04679673,  0.01039904,  0.04844381, -0.03644277,  0.04247322,
         0.04932361, -0.00382499, -0.02198377, -0.02290235, -0.00016351],
       [-0.0372941 , -0.03828514,  0.00622058, -0.00144024, -0.01045423,
        -0.02724336, -0.02563229,  0.0025424 ,  0.04759748, -0.01440148],
       [ 0.04508236, -0.00846624,  0.04136162, -0.0256164 ,  0.04415221,
         0.03130234,  0.03808018,  0.03918136, -0.00148093,  0.02065933],
       [ 0.01744771,  0.04932345,  0.01297107, -0.01691844, -0.01965203,
         0.00579583, -0.00503425, -0.02690699